name: Typos Check
on:
  push:
  pull_request:
jobs:
  typos-check:
    name: Spell Check with Typos
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check spelling with custom config file
        run: |
          exit 1
